#!/bin/bash

set -e
set -o pipefail

if [[ ! -f bin/solve.py ]]
then
    echo "Must be run from top of zoomtiles checkout"
    exit 1
fi

function usage() {
    echo "Usage: solve|test"
    exit 1
}
if [[ "$#" -eq 0 ]]
then
    usage
fi

export PYTHONPATH=$(pwd)/lib
action="$1"
shift


if [[ "$action" == "solve" ]]
then
    exec ./bin/solve.py "$@"
elif [[ "$action" == "test" ]]
then
    exec python -m unittest  discover -v -s lib
else
    usage
fi
